name: improving-exoplanet-radii
channels:
  - defaults
  - conda-forge
dependencies:
  - python >= 3.6
  - pip
  - numpy < 1.22
  - astropy
  - pandas
  - scipy
  - seaborn
  - matplotlib
  - jupyter
  - exoplanet
  - aesara-theano-fallback
  - pip:
    - lightkurve
    - pymc3-ext
    - corner
    - cloudpickle
    - celerite2
    - arviz
